//
// Generated file, do not edit! Created by opp_msgc 4.3 from attacks/controlmessages/droppingAttack/NA_DroppingMessage.msg.
//

#ifndef _NA_DROPPINGMESSAGE_M_H_
#define _NA_DROPPINGMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>attacks/controlmessages/droppingAttack/NA_DroppingMessage.msg</tt> by opp_msgc.
 * <pre>
 * message NA_DroppingMessage {
 *     double droppingAttackProbability; 
 * }
 * </pre>
 */
class NA_DroppingMessage : public ::cMessage
{
  protected:
    double droppingAttackProbability_var;

  private:
    void copy(const NA_DroppingMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NA_DroppingMessage&);

  public:
    NA_DroppingMessage(const char *name=NULL, int kind=0);
    NA_DroppingMessage(const NA_DroppingMessage& other);
    virtual ~NA_DroppingMessage();
    NA_DroppingMessage& operator=(const NA_DroppingMessage& other);
    virtual NA_DroppingMessage *dup() const {return new NA_DroppingMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual double getDroppingAttackProbability() const;
    virtual void setDroppingAttackProbability(double droppingAttackProbability);
};

inline void doPacking(cCommBuffer *b, NA_DroppingMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NA_DroppingMessage& obj) {obj.parsimUnpack(b);}


#endif // _NA_DROPPINGMESSAGE_M_H_
