//
// Generated file, do not edit! Created by nedtool 4.6 from attacks/controlmessages/droppingAttack/NA_DroppingMessage.msg.
//

#ifndef _NA_DROPPINGMESSAGE_M_H_
#define _NA_DROPPINGMESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>attacks/controlmessages/droppingAttack/NA_DroppingMessage.msg:29</tt> by nedtool.
 * <pre>
 * //
 * // Message interchanged between dropping attack controller and the corresponding hacked
 * // modules. In this case NA_IPv4
 * //
 * // @see NA_DroppingAttack, NA_IPv4
 * //
 * // @author Gabriel Maciá Fernández, gmacia@ugr.es
 * // @date 01/22/2013
 * message NA_DroppingMessage
 * {
 *     double droppingAttackProbability; // Attack probability
 * }
 * </pre>
 */
class NA_DroppingMessage : public ::cMessage
{
  protected:
    double droppingAttackProbability_var;

  private:
    void copy(const NA_DroppingMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NA_DroppingMessage&);

  public:
    NA_DroppingMessage(const char *name=NULL, int kind=0);
    NA_DroppingMessage(const NA_DroppingMessage& other);
    virtual ~NA_DroppingMessage();
    NA_DroppingMessage& operator=(const NA_DroppingMessage& other);
    virtual NA_DroppingMessage *dup() const {return new NA_DroppingMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual double getDroppingAttackProbability() const;
    virtual void setDroppingAttackProbability(double droppingAttackProbability);
};

inline void doPacking(cCommBuffer *b, NA_DroppingMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NA_DroppingMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef _NA_DROPPINGMESSAGE_M_H_

