//
// Generated file, do not edit! Created by nedtool 4.6 from hackedmodules/networklayer/manetrouting/aodv/NA_aodv_msg_struct.msg.
//

#ifndef _NA_AODV_MSG_STRUCT_M_H_
#define _NA_AODV_MSG_STRUCT_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "NA_aodv_msg_struct.h"
#include "ManetAddress.h"
// }}


#endif // ifndef _NA_AODV_MSG_STRUCT_M_H_

